# Generated by Django 4.2.7 on 2023-11-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitaminpresent', models.CharField(max_length=200)),
                ('type2', models.CharField(max_length=150)),
                ('name1', models.CharField(max_length=200)),
            ],
        ),
    ]
